### PR TITLE
Add CakePHP framework integration

### PR DESCRIPTION
**Pull request by dereuromark**
Thank you for the great library :)

Demo/Showcase is also now online:
https://sandbox.dereuromark.de/sandbox/qr-code-examples

### CODE REVIEW

**Comment by codemasher** [comment]
Oh hey that's nice! A suggestion for your library: add [the option `connectPaths`](https://php-qrcode.readthedocs.io/en/main/Usage/Configuration-settings.html#connectpaths) to the SVG options to avoid [hairlines between the modules/layers](https://github.com/chillerlan/php-qrcode/issues/57).

**Comment by dereuromark** [comment]
Fixed it :) Thx!

**Comment by dereuromark** [comment]
I also proposed this for https://github.com/ziadoz/awesome-php/pull/1280 if that's all right.
There was no QR code topic yet.

**Comment by codemasher** [comment]
Oh thank you!

**Pull request merged**
