### PR TITLE
Add namespace to README.md example

### PR DESCRIPTION
**Pull request by qqux**
Yeah, this is pretty self-explanatory.

### CODE REVIEW

**Comment by codemasher** [comment]
Namespaces were left out intentionally to not clutter the readme. Users may refer to the [examples](https://github.com/chillerlan/php-qrcode/tree/master/examples) for additional info.

**Comment by qqux** [comment]
> 
> 
> Namespaces were left out intentionally to not clutter the readme. Users may refer to the [examples](https://github.com/chillerlan/php-qrcode/tree/master/examples) for additional info.

Yes. That's where I had to dig in to find it. I thought it's an omission so I created a PR to rectify it.

Honestly, specifying the namespace is the first thing to do in every README, yet alone for a library for which 99% of the use case is one line specified in "Usage" section. This is the only PHP library I've run across so far that doesn't do it. It makes no sense to me but if your decision is to intentionally make your library harder to use, let it be.

**Comment by codemasher** [comment]
There are literal working examples and that's pointed out in the readme too. If you have problems using namespaces that's not this library's fault, sorry.

**Comment by qqux** [comment]
> 
> 
> There are literal working examples and that's pointed out in the readme too. If you have problems using namespaces that's not this library's fault, sorry.

You're missing the entire point. There is literally everything in the README. Every method, every property, literally everything except the one thing required to use it all - the namespace.

But as I said, it's your decision and I have moved on regardless.

**Comment by codemasher** [comment]
Bye!

**Pull request closed without merging**
