### PR TITLE
Add PHP-CS fixer and lint the codebase

### PR DESCRIPTION
**Pull request by X-Coder264**
The current codebase currently has a very old codestyle. This PR brings it up to speed so that it's PSR-2 compliant.

### CODE REVIEW

**Comment by codemasher** [comment]
nope. i refuse to adhere to PSR-2/12 as it is an incnosistent outdated mess.

**Comment by X-Coder264** [comment]
PSR-12 became the new standard in August last year and it replaced PSR-2 so I don't see how it could possibly be "outdated". It's so fresh that PHP-CS fixer doesn't even have all PSR-12 fixers implemented yet. Also most of the community uses PSR-2/12. If it was that bad nobody would use it, but whatever, your lib - your choice of codestyle.

**Comment by codemasher** [comment]
Just as a clarification: PSR-2 (and 12) don't add any value - not even the always proclaimed "ease of collaboration" - and it starts only with [spaces over tabs](https://lea.verou.me/2012/01/why-tabs-are-clearly-superior/), a lot of which the working group could have fixed in PSR-12. In this essay i will

**Comment by codemasher** [comment]
Also a reminder that not because "everyone is using/adhering to it" does make something make actually good.

**Comment by X-Coder264** [comment]
I'm not saying that just because everyone is adhering to it that is's good. Unlike you I don't think those PSRs are bad at all. You say that they don't bring any value, not eve easier collaboration. I strongly disagree. As a regular Laravel and Symfony contributor (both of which adhere to those PSRs) when I open this codebase it looks messy as hell at first. That makes code harder to read and that makes it harder to understand which makes it harder to contribute to.

I don't have any intentions of discussing this further as it's pointless.

**Comment by codemasher** [comment]
Look, i've been maintaining this library for years now and this is the first complaint about the code style i've received. I understand that it might be your preference to adhere to a code style that actually makes it harder to read and edit code but somehow is accepted by the community. However, anyone who has contributed code to this library before did not only seem to have no problems to understand the codebase, but also adhere to the code style i chose. What i might do at some point is to add a  PHPStorm options file so that others could use the same code style in their forks. And i will die on that hill.

**Pull request closed without merging**
